/* Process model C form file: Yu_wh_pgq.pr.c */
/* Portions of this file copyright 1986-2011 by OPNET Technologies, Inc. */


/*
 =========================== NOTE ==========================
 This file is automatically generated from Yu_wh_pgq.pr.m
 during a process model compilation.

 Do NOT manually edit this file.
 Manual edits will be lost during the next compilation.
 =========================== NOTE ==========================
*/



/* This variable carries the header into the object file */
const char Yu_wh_pgq_pr_c [] = "MIL_3_Tfile_Hdr_ 171A 30A modeler 7 5509B9D1 5509B9D1 1 ECE-PHO305-01 chenyua 0 0 none none 0 0 none 0 0 0 0 0 0 0 0 2b1a 1                                                                                                                                                                                                                                                                                                                                                                                                    ";
#include <string.h>



/* OPNET system definitions */
#include <opnet.h>



/* Header Block */

// ? #define a self initialization trigger


// define packet arrival signal here
#define PK_ARRVL (op_intrpt_type () == OPC_INTRPT_STRM)

// define packet receives at the destination here
#define DEST_REACHED (op_intrpt_type () == OPC_INTRPT_REMOTE)

// get the handshake signale here
#define ROUTER_READY (op_intrpt_type () == OPC_INTRPT_STAT)

// define the time out handler
#define TIME_OUT (op_intrpt_type () == OPC_INTRPT_SELF)


#define SEND_NEXT_FLIT send_next_flit();

#define RECEIVE_FLIT receive_flit();

#define HANDLE_TIME_OUT handle_time_out();

#define SCHEDULE_TF schedule_tf();



// define flit type here
#define Flit_Type_Data_Flit 0
#define Flit_Type_Dest_Addr 1
#define Flit_Type_Src_Addr 2
#define Flit_Type_Worm_Length 6
#define Flit_Type_Tail 7

/* packet stream definitions */
#define RCV_IN_STRM 0
#define SRC_IN_STRM 1
#define XMT_OUT_STRM 0

/* transition macros */
#define SRC_ARRVL (ev_type == OPC_INTRPT_STRM && ev_strm == SRC_IN_STRM)
#define RCV_ARRVL (ev_type == OPC_INTRPT_STRM && ev_strm == RCV_IN_STRM)

// define node number range
#define MIN_NODE_NUMBER 0
#define MAX_NODE_NUMBER 64

/* End of Header Block */

#if !defined (VOSD_NO_FIN)
#undef	BIN
#undef	BOUT
#define	BIN		FIN_LOCAL_FIELD(_op_last_line_passed) = __LINE__ - _op_block_origin;
#define	BOUT	BIN
#define	BINIT	FIN_LOCAL_FIELD(_op_last_line_passed) = 0; _op_block_origin = __LINE__;
#else
#define	BINIT
#endif /* #if !defined (VOSD_NO_FIN) */



/* State variable definitions */
typedef struct
	{
	/* Internal state tracking for FSM */
	FSM_SYS_STATE
	/* State Variables */
	char	                   		router_ready_statewire                          ;
	int	                    		this_node_address                               ;
	} Yu_wh_pgq_state;

#define router_ready_statewire  		op_sv_ptr->router_ready_statewire
#define this_node_address       		op_sv_ptr->this_node_address

/* These macro definitions will define a local variable called	*/
/* "op_sv_ptr" in each function containing a FIN statement.	*/
/* This variable points to the state variable data structure,	*/
/* and can be used from a C debugger to display their values.	*/
#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE
#define FIN_PREAMBLE_DEC	Yu_wh_pgq_state *op_sv_ptr;
#define FIN_PREAMBLE_CODE	\
		op_sv_ptr = ((Yu_wh_pgq_state *)(OP_SIM_CONTEXT_PTR->_op_mod_state_ptr));


/* Function Block */

#if !defined (VOSD_NO_FIN)
enum { _op_block_origin = __LINE__ + 2};
#endif


void handle_time_out(void){
	int intrpt_code;
	
	FIN(handle_time_out());
	
	intrpt_code = op_intrpt_code();
	
	//tail flit is transmitted
	if (intrpt_code == 1) {
	
	
	// otherwise generating another message
	} else if (intrpt_code == 2) {
	
	
	}
	
	FOUT;
}

Packet * generate_flit(int type, int data){
	Packet * pkptr;
	
	FIN(generate_flit());
	
	pkptr = op_pk_create_fmt("Yu_wh_pkformat");
	op_pk_nfd_set(pkptr, "type", type);
	op_pk_nfd_set(pkptr, "data", data);
	
	FRET(pkptr);
}

void schedule_tf(void){
	Packet * pkptr;

	FIN(schedule_tf());
	
	pkptr = generate_flit(Flit_Type_Tail, 11);
	op_subq_pk_insert(0, pkptr, OPC_QPOS_TAIL);
	
	
	FOUT;
}

void generate_message_enqueue(void){
	Packet * pkptr;
	int dest_address;
	int message_length;
	
	FIN(generate_message());
	
	do {
		dest_address = (int)op_dist_outcome(op_dist_load("uniform_int", MIN_NODE_NUMBER, MAX_NODE_NUMBER));
	
	}while(dest_address == this_node_address);
	
	// generate destination flit
	pkptr = generate_flit(Flit_Type_Dest_Addr, dest_address);
	op_subq_pk_insert(0, pkptr, OPC_QPOS_TAIL);
	
	pkptr = generate_flit(Flit_Type_Dest_Addr, this_node_address);
	op_subq_pk_insert(0, pkptr, OPC_QPOS_TAIL);
	
	message_length = 200;
	pkptr = generate_flit(Flit_Type_Worm_Length, message_length);
	op_subq_pk_insert(0, pkptr, OPC_QPOS_TAIL);
	
	for(;message_length >=0; message_length--) {
		pkptr = generate_flit(Flit_Type_Data_Flit, message_length);
		op_subq_pk_insert(0, pkptr, OPC_QPOS_TAIL);
	}
	
	
	FOUT;
}

void send_next_flit(){
	Packet * pkptr;
	
	int intrpt_code;
	
	FIN(send_next_flit());
	
	intrpt_code = op_intrpt_code();
	
	if (op_subq_empty(0) == OPC_FALSE){
		pkptr = op_subq_pk_remove(0, OPC_QPOS_HEAD);
	}else {
		pkptr = generate_flit(Flit_Type_Data_Flit, 11);
	}
	
	op_pk_send(pkptr, XMT_OUT_STRM);
	
	FOUT;
}



















/* End of Function Block */

/* Undefine optional tracing in FIN/FOUT/FRET */
/* The FSM has its own tracing code and the other */
/* functions should not have any tracing.		  */
#undef FIN_TRACING
#define FIN_TRACING

#undef FOUTRET_TRACING
#define FOUTRET_TRACING

#if defined (__cplusplus)
extern "C" {
#endif
	void Yu_wh_pgq (OP_SIM_CONTEXT_ARG_OPT);
	VosT_Obtype _op_Yu_wh_pgq_init (int * init_block_ptr);
	void _op_Yu_wh_pgq_diag (OP_SIM_CONTEXT_ARG_OPT);
	void _op_Yu_wh_pgq_terminate (OP_SIM_CONTEXT_ARG_OPT);
	VosT_Address _op_Yu_wh_pgq_alloc (VosT_Obtype, int);
	void _op_Yu_wh_pgq_svar (void *, const char *, void **);


#if defined (__cplusplus)
} /* end of 'extern "C"' */
#endif




/* Process model interrupt handling procedure */


void
Yu_wh_pgq (OP_SIM_CONTEXT_ARG_OPT)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	FIN_MT (Yu_wh_pgq ());

		{
		/* Temporary Variables */
		int ev_type, ev_strm;
		
		/* End of Temporary Variables */


		FSM_ENTER ("Yu_wh_pgq")

		FSM_BLOCK_SWITCH
			{
			/*---------------------------------------------------------*/
			/** state (init) enter executives **/
			FSM_STATE_ENTER_FORCED_NOLABEL (0, "init", "Yu_wh_pgq [init enter execs]")
				FSM_PROFILE_SECTION_IN ("Yu_wh_pgq [init enter execs]", state0_enter_exec)
				{
				// read in the values for the run-time attributes
				
				// generate a self interrupt here to send a message
				
				
				// get this node address
				this_node_address = 0;
				}
				FSM_PROFILE_SECTION_OUT (state0_enter_exec)

			/** state (init) exit executives **/
			FSM_STATE_EXIT_FORCED (0, "init", "Yu_wh_pgq [init exit execs]")


			/** state (init) transition processing **/
			FSM_TRANSIT_FORCE (1, state1_enter_exec, ;, "default", "", "init", "idle", "tr_0", "Yu_wh_pgq [init -> idle : default / ]")
				/*---------------------------------------------------------*/



			/** state (idle) enter executives **/
			FSM_STATE_ENTER_UNFORCED (1, "idle", state1_enter_exec, "Yu_wh_pgq [idle enter execs]")

			/** blocking after enter executives of unforced state. **/
			FSM_EXIT (3,"Yu_wh_pgq")


			/** state (idle) exit executives **/
			FSM_STATE_EXIT_UNFORCED (1, "idle", "Yu_wh_pgq [idle exit execs]")
				FSM_PROFILE_SECTION_IN ("Yu_wh_pgq [idle exit execs]", state1_exit_exec)
				{
				// judge the interrupt type and stream type here
				
				ev_type = op_intrpt_type();
				if (ev_type == OPC_INTRPT_STRM)
				   ev_strm = op_intrpt_strm();
				}
				FSM_PROFILE_SECTION_OUT (state1_exit_exec)


			/** state (idle) transition processing **/
			FSM_PROFILE_SECTION_IN ("Yu_wh_pgq [idle trans conditions]", state1_trans_conds)
			FSM_INIT_COND (ROUTER_READY)
			FSM_TEST_COND (DEST_REACHED)
			FSM_TEST_COND (TIME_OUT)
			FSM_DFLT_COND
			FSM_TEST_LOGIC ("idle")
			FSM_PROFILE_SECTION_OUT (state1_trans_conds)

			FSM_TRANSIT_SWITCH
				{
				FSM_CASE_TRANSIT (0, 1, state1_enter_exec, SEND_NEXT_FLIT;, "ROUTER_READY", "SEND_NEXT_FLIT", "idle", "idle", "tr_2", "Yu_wh_pgq [idle -> idle : ROUTER_READY / SEND_NEXT_FLIT]")
				FSM_CASE_TRANSIT (1, 1, state1_enter_exec, SCHEDULE_TF;, "DEST_REACHED", "SCHEDULE_TF", "idle", "idle", "tr_3", "Yu_wh_pgq [idle -> idle : DEST_REACHED / SCHEDULE_TF]")
				FSM_CASE_TRANSIT (2, 1, state1_enter_exec, HANDLE_TIME_OUT;, "TIME_OUT", "HANDLE_TIME_OUT", "idle", "idle", "tr_4", "Yu_wh_pgq [idle -> idle : TIME_OUT / HANDLE_TIME_OUT]")
				FSM_CASE_TRANSIT (3, 1, state1_enter_exec, ;, "default", "", "idle", "idle", "tr_5", "Yu_wh_pgq [idle -> idle : default / ]")
				}
				/*---------------------------------------------------------*/



			}


		FSM_EXIT (0,"Yu_wh_pgq")
		}
	}




void
_op_Yu_wh_pgq_diag (OP_SIM_CONTEXT_ARG_OPT)
	{
	/* No Diagnostic Block */
	}




void
_op_Yu_wh_pgq_terminate (OP_SIM_CONTEXT_ARG_OPT)
	{

	FIN_MT (_op_Yu_wh_pgq_terminate ())


	/* No Termination Block */

	Vos_Poolmem_Dealloc (op_sv_ptr);

	FOUT
	}


/* Undefine shortcuts to state variables to avoid */
/* syntax error in direct access to fields of */
/* local variable prs_ptr in _op_Yu_wh_pgq_svar function. */
#undef router_ready_statewire
#undef this_node_address

#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE

#define FIN_PREAMBLE_DEC
#define FIN_PREAMBLE_CODE

VosT_Obtype
_op_Yu_wh_pgq_init (int * init_block_ptr)
	{
	VosT_Obtype obtype = OPC_NIL;
	FIN_MT (_op_Yu_wh_pgq_init (init_block_ptr))

	obtype = Vos_Define_Object_Prstate ("proc state vars (Yu_wh_pgq)",
		sizeof (Yu_wh_pgq_state));
	*init_block_ptr = 0;

	FRET (obtype)
	}

VosT_Address
_op_Yu_wh_pgq_alloc (VosT_Obtype obtype, int init_block)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	Yu_wh_pgq_state * ptr;
	FIN_MT (_op_Yu_wh_pgq_alloc (obtype))

	ptr = (Yu_wh_pgq_state *)Vos_Alloc_Object (obtype);
	if (ptr != OPC_NIL)
		{
		ptr->_op_current_block = init_block;
#if defined (OPD_ALLOW_ODB)
		ptr->_op_current_state = "Yu_wh_pgq [init enter execs]";
#endif
		}
	FRET ((VosT_Address)ptr)
	}



void
_op_Yu_wh_pgq_svar (void * gen_ptr, const char * var_name, void ** var_p_ptr)
	{
	Yu_wh_pgq_state		*prs_ptr;

	FIN_MT (_op_Yu_wh_pgq_svar (gen_ptr, var_name, var_p_ptr))

	if (var_name == OPC_NIL)
		{
		*var_p_ptr = (void *)OPC_NIL;
		FOUT
		}
	prs_ptr = (Yu_wh_pgq_state *)gen_ptr;

	if (strcmp ("router_ready_statewire" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->router_ready_statewire);
		FOUT
		}
	if (strcmp ("this_node_address" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->this_node_address);
		FOUT
		}
	*var_p_ptr = (void *)OPC_NIL;

	FOUT
	}

