/* Process model C form file: Yu_wh_psq.pr.c */
/* Portions of this file copyright 1986-2011 by OPNET Technologies, Inc. */


/*
 =========================== NOTE ==========================
 This file is automatically generated from Yu_wh_psq.pr.m
 during a process model compilation.

 Do NOT manually edit this file.
 Manual edits will be lost during the next compilation.
 =========================== NOTE ==========================
*/



/* This variable carries the header into the object file */
const char Yu_wh_psq_pr_c [] = "MIL_3_Tfile_Hdr_ 171A 30A modeler 7 5509C02E 5509C02E 1 ECE-PHO305-01 chenyua 0 0 none none 0 0 none 0 0 0 0 0 0 0 0 2b1a 1                                                                                                                                                                                                                                                                                                                                                                                                    ";
#include <string.h>



/* OPNET system definitions */
#include <opnet.h>



/* Header Block */


// define arrival signal here
#define ARRIVAL (op_intrpt_type() == OPC_INTRPT_STRM)


// define flit receiving function here
#define RECEIVE_FLIT receive_flit_in_squeue();


// define flit type here
#define Flit_Type_Data_Flit 0
#define Flit_Type_Dest_Addr 1
#define Flit_Type_Src_Addr 2
#define Flit_Type_Worm_Length 6
#define Flit_Type_Tail 7


/* packet stream definitions */
#define RCV_IN_STRM 0
#define SRC_IN_STRM 1
#define XMT_OUT_STRM 0

/* transition macros */
#define SRC_ARRVL (ev_type == OPC_INTRPT_STRM && ev_strm == SRC_IN_STRM)
#define RCV_ARRVL (ev_type == OPC_INTRPT_STRM && ev_strm == RCV_IN_STRM)



/* End of Header Block */

#if !defined (VOSD_NO_FIN)
#undef	BIN
#undef	BOUT
#define	BIN		FIN_LOCAL_FIELD(_op_last_line_passed) = __LINE__ - _op_block_origin;
#define	BOUT	BIN
#define	BINIT	FIN_LOCAL_FIELD(_op_last_line_passed) = 0; _op_block_origin = __LINE__;
#else
#define	BINIT
#endif /* #if !defined (VOSD_NO_FIN) */



/* State variable definitions */
typedef struct
	{
	/* Internal state tracking for FSM */
	FSM_SYS_STATE
	/* State Variables */
	Stathandle	             		ete_gsh                                         ;
	} Yu_wh_psq_state;

#define ete_gsh                 		op_sv_ptr->ete_gsh

/* These macro definitions will define a local variable called	*/
/* "op_sv_ptr" in each function containing a FIN statement.	*/
/* This variable points to the state variable data structure,	*/
/* and can be used from a C debugger to display their values.	*/
#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE
#define FIN_PREAMBLE_DEC	Yu_wh_psq_state *op_sv_ptr;
#define FIN_PREAMBLE_CODE	\
		op_sv_ptr = ((Yu_wh_psq_state *)(OP_SIM_CONTEXT_PTR->_op_mod_state_ptr));


/* Function Block */

#if !defined (VOSD_NO_FIN)
enum { _op_block_origin = __LINE__ + 2};
#endif


void discard_rcv_queue(void){
	
	Packet * pkptr;
	int flit_type;
	FIN(discard_rcv_queue());
	
	do {
		if (!op_subq_empty (0)) {
			pkptr = op_subq_pk_remove(0, OPC_QPOS_HEAD);
			flit_type = op_pk_nfd_get(pkptr, "type", &flit_type);
			op_pk_destroy(pkptr);
		} else{
			break;
		}
	} while (flit_type != Flit_Type_Tail);
		
	FOUT;
}




void deal_with_statistics(Packet * pkptr){
	double ete_delay;
	
	FIN(deal_with_statistics());
	ete_delay = op_sim_time () - op_pk_creation_time_get (pkptr);
    op_stat_write (ete_gsh, ete_delay);

	FOUT;
}

void receive_flit_in_squeue(void){
	Packet * pkptr;
	int flit_type;
	FIN(receive_flit_in_squeue());
	
	pkptr = op_pk_get(op_intrpt_strm());
	
	// get teh statistics data
	deal_with_statistics(pkptr);
	
	// insert into the receiving queue
	op_subq_pk_insert(0, pkptr, OPC_QPOS_TAIL);
	
	// get the receiving flit type
	op_pk_nfd_get(pkptr, "type", &flit_type);
	
	
	if(flit_type == Flit_Type_Dest_Addr) {
	// if the flit is destination address flit, then 
	
	
	
	} else if (flit_type == Flit_Type_Src_Addr) {
	// if the flit contains source address, then trigger remote intrrupt to PGQueue
	// of the source node
	
	} else if (flit_type == Flit_Type_Tail) {
	// if the flit is a tail, then discard the flits in the receiving queue
	
	discard_rcv_queue();
	}
	
	
	
	FOUT;
}





















/* End of Function Block */

/* Undefine optional tracing in FIN/FOUT/FRET */
/* The FSM has its own tracing code and the other */
/* functions should not have any tracing.		  */
#undef FIN_TRACING
#define FIN_TRACING

#undef FOUTRET_TRACING
#define FOUTRET_TRACING

#if defined (__cplusplus)
extern "C" {
#endif
	void Yu_wh_psq (OP_SIM_CONTEXT_ARG_OPT);
	VosT_Obtype _op_Yu_wh_psq_init (int * init_block_ptr);
	void _op_Yu_wh_psq_diag (OP_SIM_CONTEXT_ARG_OPT);
	void _op_Yu_wh_psq_terminate (OP_SIM_CONTEXT_ARG_OPT);
	VosT_Address _op_Yu_wh_psq_alloc (VosT_Obtype, int);
	void _op_Yu_wh_psq_svar (void *, const char *, void **);


#if defined (__cplusplus)
} /* end of 'extern "C"' */
#endif




/* Process model interrupt handling procedure */


void
Yu_wh_psq (OP_SIM_CONTEXT_ARG_OPT)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	FIN_MT (Yu_wh_psq ());

		{
		/* Temporary Variables */
		int   ev_type, ev_strm;
		/* End of Temporary Variables */


		FSM_ENTER ("Yu_wh_psq")

		FSM_BLOCK_SWITCH
			{
			/*---------------------------------------------------------*/
			/** state (st_4) enter executives **/
			FSM_STATE_ENTER_FORCED_NOLABEL (0, "st_4", "Yu_wh_psq [st_4 enter execs]")
				FSM_PROFILE_SECTION_IN ("Yu_wh_psq [st_4 enter execs]", state0_enter_exec)
				{
				ete_gsh = op_stat_reg ("ETE Delay", OPC_STAT_INDEX_NONE, OPC_STAT_GLOBAL);
				}
				FSM_PROFILE_SECTION_OUT (state0_enter_exec)

			/** state (st_4) exit executives **/
			FSM_STATE_EXIT_FORCED (0, "st_4", "Yu_wh_psq [st_4 exit execs]")


			/** state (st_4) transition processing **/
			FSM_TRANSIT_FORCE (1, state1_enter_exec, ;, "default", "", "st_4", "st_5", "tr_3", "Yu_wh_psq [st_4 -> st_5 : default / ]")
				/*---------------------------------------------------------*/



			/** state (st_5) enter executives **/
			FSM_STATE_ENTER_UNFORCED (1, "st_5", state1_enter_exec, "Yu_wh_psq [st_5 enter execs]")

			/** blocking after enter executives of unforced state. **/
			FSM_EXIT (3,"Yu_wh_psq")


			/** state (st_5) exit executives **/
			FSM_STATE_EXIT_UNFORCED (1, "st_5", "Yu_wh_psq [st_5 exit execs]")
				FSM_PROFILE_SECTION_IN ("Yu_wh_psq [st_5 exit execs]", state1_exit_exec)
				{
				ev_type = op_intrpt_type();
				if (ev_type == OPC_INTRPT_STRM)
				   ev_strm = op_intrpt_strm();
				
				
				
				
				
				}
				FSM_PROFILE_SECTION_OUT (state1_exit_exec)


			/** state (st_5) transition processing **/
			FSM_PROFILE_SECTION_IN ("Yu_wh_psq [st_5 trans conditions]", state1_trans_conds)
			FSM_INIT_COND (ARRIVAL)
			FSM_DFLT_COND
			FSM_TEST_LOGIC ("st_5")
			FSM_PROFILE_SECTION_OUT (state1_trans_conds)

			FSM_TRANSIT_SWITCH
				{
				FSM_CASE_TRANSIT (0, 1, state1_enter_exec, RECEIVE_FLIT;, "ARRIVAL", "RECEIVE_FLIT", "st_5", "st_5", "tr_5", "Yu_wh_psq [st_5 -> st_5 : ARRIVAL / RECEIVE_FLIT]")
				FSM_CASE_TRANSIT (1, 1, state1_enter_exec, ;, "default", "", "st_5", "st_5", "tr_4", "Yu_wh_psq [st_5 -> st_5 : default / ]")
				}
				/*---------------------------------------------------------*/



			}


		FSM_EXIT (0,"Yu_wh_psq")
		}
	}




void
_op_Yu_wh_psq_diag (OP_SIM_CONTEXT_ARG_OPT)
	{
	/* No Diagnostic Block */
	}




void
_op_Yu_wh_psq_terminate (OP_SIM_CONTEXT_ARG_OPT)
	{

	FIN_MT (_op_Yu_wh_psq_terminate ())


	/* No Termination Block */

	Vos_Poolmem_Dealloc (op_sv_ptr);

	FOUT
	}


/* Undefine shortcuts to state variables to avoid */
/* syntax error in direct access to fields of */
/* local variable prs_ptr in _op_Yu_wh_psq_svar function. */
#undef ete_gsh

#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE

#define FIN_PREAMBLE_DEC
#define FIN_PREAMBLE_CODE

VosT_Obtype
_op_Yu_wh_psq_init (int * init_block_ptr)
	{
	VosT_Obtype obtype = OPC_NIL;
	FIN_MT (_op_Yu_wh_psq_init (init_block_ptr))

	obtype = Vos_Define_Object_Prstate ("proc state vars (Yu_wh_psq)",
		sizeof (Yu_wh_psq_state));
	*init_block_ptr = 0;

	FRET (obtype)
	}

VosT_Address
_op_Yu_wh_psq_alloc (VosT_Obtype obtype, int init_block)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	Yu_wh_psq_state * ptr;
	FIN_MT (_op_Yu_wh_psq_alloc (obtype))

	ptr = (Yu_wh_psq_state *)Vos_Alloc_Object (obtype);
	if (ptr != OPC_NIL)
		{
		ptr->_op_current_block = init_block;
#if defined (OPD_ALLOW_ODB)
		ptr->_op_current_state = "Yu_wh_psq [st_4 enter execs]";
#endif
		}
	FRET ((VosT_Address)ptr)
	}



void
_op_Yu_wh_psq_svar (void * gen_ptr, const char * var_name, void ** var_p_ptr)
	{
	Yu_wh_psq_state		*prs_ptr;

	FIN_MT (_op_Yu_wh_psq_svar (gen_ptr, var_name, var_p_ptr))

	if (var_name == OPC_NIL)
		{
		*var_p_ptr = (void *)OPC_NIL;
		FOUT
		}
	prs_ptr = (Yu_wh_psq_state *)gen_ptr;

	if (strcmp ("ete_gsh" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->ete_gsh);
		FOUT
		}
	*var_p_ptr = (void *)OPC_NIL;

	FOUT
	}

